version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:13.2
jobs:
  test-audit:
    executor: node
    steps:
      - checkout
      - run:
          name: Audit js
          command: npm run test:audit
  test-format:
    executor: node
    steps:
      - checkout
      - run: 
          name: Install
          command: npm ci
      - run:
          name: Test format
          command: npm run test:format
  test-lint:
    executor: node
    steps:
      - checkout
      - run:
          name: Lint js
          command: npm run test:lint
  test:
    executor: node
    steps:
      - checkout
      - run: 
          name: Install
          command: npm ci
      - run:
          name: Test
          command:
            make test
workflows:
  test:
    jobs:
      - test-audit
      - test-format
      - test-lint
      - test
